title: edmundtale
description: edmundtale web site 
repository: edmundtale/edmundtale.github.io
author:        edmund tale
url:           "https://edmundtale.github.io/"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
